---
name: CI Build
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - "**/*.nix"
      - "flake.lock"
      - "flake.nix"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      - name: Install Determinate Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build beepboop via Nix
        run: nix build .#default
