---
name: CI Build
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - "**/*.nix"
      - "**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - "flake.lock"
      - "flake.nix"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      - name: Install Determinate Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Check Nix flake
        run: nix flake check

      - name: Cargo check
        run: nix develop .#ci --command cargo check

      - name: Cargo clippy
        run: nix develop .#ci --command cargo clippy -- -D warnings

      - name: Cargo format check
        run: nix develop .#ci --command cargo fmt --check

      - name: Cargo test
        run: nix develop .#ci --command cargo test

      - name: Build beepboop via Nix
        run: nix build .#default
